---
variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=/maven/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  OUTPUT_CONTAINER_NAME: "quay.io/rblake/baaas-master-control-plane:$CI_COMMIT_SHA"

stages:
  - build
  - test
  - native-compile
  - build-and-push-container

.cache-definition: &cache-definition
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - baaas-master-control-plane-api/target
      - baaas-master-control-plane/target

build:
  <<: *cache-definition
  image: quay.io/kiegroup/kogito-quarkus-ubi8-s2i:1.0.0
  stage: build
  script:
    - "/usr/share/maven/bin/mvn compile"
  artifacts:
    expire_in: 1 week
    paths:
      - baaas-master-control-plane-api/target/checkstyle.log
      - baaas-master-control-plane/target/checkstyle.log
  tags:
    - baaas
  only:
    - main@baaas/baaas-master-control-plane
    - merge_requests@baaas/baaas-master-control-plane

test:
  <<: *cache-definition
  image: quay.io/kiegroup/kogito-quarkus-ubi8-s2i:1.0.0
  stage: test
  script:
    - "/usr/share/maven/bin/mvn test"
  artifacts:
    expire_in: 1 week
    reports:
      junit:
        - baaas-master-control-plane-api/target/surefire-reports/TEST-*.xml
        - baaas-master-control-plane/target/surefire-reports/TEST-*.xml
  tags:
    - baaas
  only:
    - main@baaas/baaas-master-control-plane
    - merge_requests@baaas/baaas-master-control-plane

native-compile:
  <<: *cache-definition
  image: quay.io/kiegroup/kogito-quarkus-ubi8-s2i:1.0.0
  stage: native-compile
  script:
    - "/usr/share/maven/bin/mvn package -Pnative -Dmaven.test.skip=true"
  artifacts:
    expire_in: 1 week
    paths:
      - baaas-master-control-plane/target/*-runner
  tags:
    - baaas
  only:
    - main@baaas/baaas-master-control-plane

build-and-push-container:
  image: docker:19.03.12
  stage: build-and-push-container
  before_script:
    - echo "$CONTAINER_REGISTRY_PASSWORD" | docker login quay.io --username $CONTAINER_REGISTRY_USER --password-stdin
  script:
    - "docker build -f baaas-master-control-plane/src/main/docker/Dockerfile.native -t $OUTPUT_CONTAINER_NAME baaas-master-control-plane/"
    - "docker push $OUTPUT_CONTAINER_NAME"
  after_script:
    - "docker image rm -f $OUTPUT_CONTAINER_NAME"
  tags:
    - baaas
  only:
    - main@baaas/baaas-master-control-plane