---
version: '3.8'
services:
  db:
    image: library/postgres:13.1
    environment:
      POSTGRES_USER: mcp
      POSTGRES_PASSWORD: mcp
      POSTGRES_DB: baaas-mcp
    ports:
      - "5432:5432"

  s3:
    image: localstack/localstack:0.11.5
    environment:
      START_WEB: 0
      SERVICES: s3
    ports:
      - "8008:4566"
