---
version: '3.8'
services:
  mcp:
    build:
      context: baaas-master-control-plane
      dockerfile: src/main/docker/Dockerfile.jvm
    environment:
      BAAAS_MCP_DB_USERNAME: mcp
      BAAAS_MCP_DB_PASSWORD: mcp
      BAAAS_MCP_DB_HOST: db
      BAAAS_CCP_DMN_JIT_URL: https://baaas-dmn-jit-baaas-dmn-jit-demo.apps.kogito-cloud.automation.rhmw.io/jitdmn
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: library/postgres:13.1
    environment:
      POSTGRES_USER: mcp
      POSTGRES_PASSWORD: mcp
      POSTGRES_DB: baaas-mcp
    ports:
      - "5432:5432"
